dist: trusty
language: c
sudo: false

notifications:
  email:
    recipients:
      - steveri@stanford.edu
    # on_success: never # default: change
    on_failure: always # default: always

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

install:
  # Current working directory: /home/travis/build/StanfordAHA/fftgen

  # (verilator, csh) already installed above ("addons/apt" section)

  # Genesis2
  - source bin/setup_genesis.sh

script:
  # set -e => exit on failure "you can sandwich stuff in script w/ set -e and set +e."
  - set -e

  # 47/48 tests should run and pass; 48th test is *supposed* to fail

  - mkdir regression; cd regression
  # - ls -l ../bin
  # - ../bin/golden_test.csh -sim verilator 8 1 1port |& tee test_results.log
  - ../bin/golden_test.csh -sim verilator |& tee test_results.log | egrep 'PASS|FAIL|ERR'
  # - cat /tmp/test_8_1_1port.log
  # - ls -l fft.log; wc -l fft.log; grep "Wrote" fft.log
  # - cat /tmp/golden_test_8_1_1port.log
  - egrep 'FAIL|ERR' test_results.log && exit 13


