name: CI

########################################################################
on:
  # Every push
  push:

  # When requested manually
  workflow_dispatch:

  # Schedule NOTE ONLY WORKS FOR MAIN BRANCH :(
  schedule:
    # Every morning at 3am ( 3am local ~ 10am UTC :( )
    # ( min hr day JAN-DEC MON-SUN )
    - cron: '0 10 * * *'


########################################################################
jobs:

  # This workflow contains a single job called "CI"
  CI:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      # Action, branch, and repo information.
      - run: echo Action = ${{ github.event_name }}, branch = ${{ github.ref }}
      # - run: echo "Branch '${{ github.ref }}' in repo '${{ github.repository }}'."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install csh
        run: sudo apt-get install csh

      - name: Install Genesis2
        run: source bin/setup_genesis.sh

      - name: Install verilator
        run: sudo apt-get install verilator

      - name: 'FFT REGRESSIONS'
        run: |
          # FFT REGRESSIONS

          # Echo commands; exit on failure
          set -x; set -e

          # Where are we?
          TRAVIS_BUILD_DIR=`pwd`

          # Initialize Genesis2 environment
          source bin/setup_genesis.sh

          # Fetch the FPU
          test -e rtl/lib && unlink rtl/lib
          git clone https://github.com/steveri/fpu rtl/lib

          # Run the regressions
          mkdir regression; cd regression
          nobuf='stdbuf -oL -eL'
          do_test='../bin/golden_test.csh -sim verilator'
          # ../bin/golden_test.csh -sim verilator |& $nobuf tee test_results.log | $nobuf egrep 'PASS|FAIL|ERR'
          $do_test |& $nobuf tee test_results.log | $nobuf egrep 'PASS|FAIL|ERR'

          # tee_results='stdbuf -oL -eL tee test_results.log'
          # filter_results="stdbuf -oL -eL egrep 'PASS|FAIL|ERR'"
          # $do_test | $tee_results | $filter_results


          wc -l test_results.log



          # Here's a tricky thing...it passes when it fails and it fails when it passes :(
          # Also---FIXME---above command should be responsible for PASS/FAIL exit codes
          egrep 'FAIL|ERR' test_results.log && exit 13 || echo okay


          


          ### SIMV ANALYZER
          # I have this test for the analyzer, why not use it.
          cd ${TRAVIS_BUILD_DIR}/bin/simv_analysis; make test


#       - name: 'FPU tests: SUB'
#         run: |
#           cd test
#           make clean
# 
#           echo "========================================================================"
#           echo "make build TEST=SUB"
#           echo "========================================================================"
#           make build TEST=SUB
# 
#           echo "========================================================================"
#           echo "make run TEST=SUB"
#           echo "========================================================================"
#           make run TEST=SUB |& tee ../test-results.sub
# 
#       - name: 'FPU tests: MUL'
#         run: |
#           cd test
#           make clean
# 
#           echo "========================================================================"
#           echo "make build TEST=MUL"
#           echo "========================================================================"
#           make build TEST=MUL
# 
#           echo "========================================================================"
#           echo "make run TEST=MUL"
#           echo "========================================================================"
#           make run TEST=MUL |& tee ../test-results.mul
# 
#       - name: Test results
#         run: |
#           echo
#           echo "ADD-TEST RESULTS"
#           sed -n '/^Num/,/^Max/p' test-results.add; tail -1 test-results.add
#           echo "================================================================================"
#           echo "SUB-TEST RESULTS"
#           sed -n '/^Num/,/^Max/p' test-results.sub; tail -1 test-results.sub
#           echo "================================================================================"
#           echo "MUL-TEST RESULTS"
#           sed -n '/^Num/,/^Max/p' test-results.mul; tail -1 test-results.mul
